name: Absensi Otomatis

on:
  schedule:
    # Senin 10.45 WIB (Mikroprocessor dan Teknik Antarmuka)
    - cron: '45 3 * * 1'
    
    # Senin 14.00 WIB (Perancangan Infrastruktur Jaringan)
    - cron: '0 7 * * 1' 

    # Rabu 14.00 WIB (Technopreneurship, Proyek Technopreneurship)
    - cron: '0 7 * * 3'

    # Rabu 16.35 WIB (Metodologi Penelitian)
    - cron: '35 9 * * 3'

    # Kamis 08.00 WIB (Pattern Recognition)
    - cron: '0 1 * * 4'

    # Kamis 10.45 WIB (Komputasi kinerja tinggi)
    - cron: '45 3 * * 4'

    # Sabtu 14.00 WIB (Internet of Things, Praktikum IoT)
    - cron: '0 7 * * 6'

  workflow_dispatch:

jobs:
  absen:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repo
        uses: actions/checkout@v4

      - name: 2. Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: 3. Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 4. Install dependencies
        run: pip install selenium ddddocr python-dotenv

      - name: 5. Jalankan absen_runner.py
        env:
          NPM: ${{ secrets.NPM }}
          PASSWORD: ${{ secrets.PASSWORD }}
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: python -u absen_runner.py